In [125]:
import pandas as pd
import sqlalchemy as sa
from sqlalchemy import create_engine

In [126]:
mmr_data = 'mmr_rates.csv'
aut_data = 'autism_rates.csv'

vax_df_one = pd.read_csv('mmr_rates.csv', encoding="ISO-8859-1")
aut_df_one = pd.read_csv('autism_rates copy.csv', encoding="ISO-8859-1", header=1)

In [127]:
vax_df_two = vax_df_one[['Names','2000','SAMPLE SIZE','2001','SAMPLE SIZE.1','2002','SAMPLE SIZE.2','2003','SAMPLE SIZE.3','2004','SAMPLE SIZE.4','2005','SAMPLE SIZE.5','2006','SAMPLE SIZE.6','2007','SAMPLE SIZE.7','2008','SAMPLE SIZE.8','2009','SAMPLE SIZE.9','2010','SAMPLE SIZE.10','2011','SAMPLE SIZE.11','2012','SAMPLE SIZE.12','2013','SAMPLE SIZE.13','2014','SAMPLE SIZE.14','2015','SAMPLE SIZE.15','2016','SAMPLE SIZE.16','2017','SAMPLE SIZE.17']].copy()

In [128]:
vax_df_two.rename(columns={
    'Names': 'state_name',
    '2000': 'mmr_rate_2000',
    'SAMPLE SIZE': 'sample_size_2000',
    '2001': 'mmr_rate_2001',
    'SAMPLE SIZE.1': 'sample_size_2001',
    '2002': 'mmr_rate_2002',
    'SAMPLE SIZE.2': 'sample_size_2002',
    '2003': 'mmr_rate_2003',
    'SAMPLE SIZE.3': 'sample_size_2003',
    '2004': 'mmr_rate_2004',
    'SAMPLE SIZE.4': 'sample_size_2004',
    '2005': 'mmr_rate_2005',
    'SAMPLE SIZE.5': 'sample_size_2005',
    '2006': 'mmr_rate_2006',
    'SAMPLE SIZE.6': 'sample_size_2006',
    '2007': 'mmr_rate_2007',
    'SAMPLE SIZE.7': 'sample_size_2007',
    '2008': 'mmr_rate_2008',
    'SAMPLE SIZE.8': 'sample_size_2008',
    '2009': 'mmr_rate_2009',
    'SAMPLE SIZE.9': 'sample_size_2009',
    '2010': 'mmr_rate_2010',
    'SAMPLE SIZE.10': 'sample_size_2010',
    '2011': 'mmr_rate_2011',
    'SAMPLE SIZE.11': 'sample_size_2011',
    '2012': 'mmr_rate_2012',
    'SAMPLE SIZE.12': 'sample_size_2012',
    '2013': 'mmr_rate_2013',
    'SAMPLE SIZE.13': 'sample_size_2013',
    '2014': 'mmr_rate_2014',
    'SAMPLE SIZE.14': 'sample_size_2014',
    '2015': 'mmr_rate_2015',
    'SAMPLE SIZE.15': 'sample_size_2015',
    '2016': 'mmr_rate_2016',
    'SAMPLE SIZE.16': 'sample_size_2016',
    '2017': 'mmr_rate_2017',
    'SAMPLE SIZE.17': 'sample_size_2017'})

,state_name,mmr_rate_2000,sample_size_2000,mmr_rate_2001,sample_size_2001,mmr_rate_2002,sample_size_2002,mmr_rate_2003,sample_size_2003,mmr_rate_2004,...,mmr_rate_2013,sample_size_2013,mmr_rate_2014,sample_size_2014,mmr_rate_2015,sample_size_2015,mmr_rate_2016,sample_size_2016,mmr_rate_2017,sample_size_2017
0,Alabama,86.8,580.0,94.3,592.0,91.6,525.0,91.2,532.0,91.8,...,89.7,166.0,92.0,237.0,95.2,272.0,91.1,249.0,92.3,295.0
1,AL-Jefferson County,87.4,294.0,93.2,277.0,91.1,258.0,94.1,252.0,89.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AL-Rest of State,86.6,286.0,94.5,315.0,91.7,267.0,90.7,280.0,92.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Alaska,87.9,295.0,87.8,292.0,88.7,262.0,90.7,278.0,89.7,...,90.5,299.0,90.2,276.0,89.7,295.0,85.6,288.0,89.3,251.0
4,Arizona,88.1,595.0,88.8,592.0,88.9,558.0,91.5,612.0,92.9,...,91.4,254.0,84.1,292.0,90.6,266.0,87.7,230.0,91.7,265.0
5,AZ-Maricopa County,87.1,307.0,88.6,295.0,91.3,290.0,92.0,318.0,91.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,AZ-Rest of State,89.7,288.0,89.1,297.0,84.8,268.0,90.7,294.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Arkansas,88.0,298.0,89.1,392.0,92.8,286.0,90.6,253.0,94.6,...,88.3,188.0,89.1,245.0,90.2,229.0,92.1,229.0,92.6,258.0
8,California,89.4,1241.0,90.8,1266.0,90.4,1101.0,92.8,1074.0,93.1,...,90.7,283.0,90.5,300.0,92.8,345.0,89.3,328.0,92.9,324.0
9,CA-Alameda County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,CA-Fresno County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,CA-Los Angeles County,92.1,332.0,90.3,329.0,91.1,276.0,95.8,256.0,94.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,CA-Northern CA Counties,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,CA-San Bernardino County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,CA-San Diego County,93.2,335.0,94.3,356.0,90.1,258.0,93.2,250.0,89.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,CA-Santa Clara County,91.0,268.0,92.0,287.0,93.0,285.0,93.2,266.0,92.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,CA-Rest of State,87.2,306.0,90.4,294.0,89.8,282.0,91.2,302.0,93.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Colorado,86.4,342.0,91.3,372.0,90.7,255.0,85.6,281.0,90.8,...,86.0,267.0,87.4,320.0,93.6,246.0,88.9,238.0,87.2,264.0
18,CO-Denver,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,CO-Rest of State,86.4,342.0,91.3,372.0,90.7,255.0,85.6,281.0,90.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Connecticut,96.1,280.0,93.8,286.0,95.3,289.0,98.4,279.0,95.0,...,91.4,213.0,93.2,237.0,97.5,250.0,94.5,267.0,94.6,266.0
21,Delaware,90.1,301.0,93.4,281.0,95.2,297.0,93.0,291.0,94.5,...,94.8,242.0,90.8,258.0,97.2,232.0,93.8,222.0,92.9,232.0
22,District of Columbia,85.1,292.0,92.6,312.0,91.2,259.0,92.8,266.0,94.6,...,96.2,223.0,90.9,280.0,92.4,321.0,93.7,309.0,94.1,269.0
23,Florida,89.0,807.0,91.1,812.0,91.1,848.0,95.2,829.0,95.4,...,93.4,228.0,91.2,227.0,90.4,273.0,91.1,273.0,91.9,314.0
24,FL-Duval County,92.6,285.0,92.6,282.0,92.1,287.0,95.5,278.0,87.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,FL-Miami-Dade County,92.1,234.0,95.0,234.0,90.7,278.0,94.9,276.0,93.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,FL-Orange County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,FL-Rest of State,88.1,288.0,90.1,296.0,91.1,283.0,95.3,275.0,96.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Georgia,90.9,562.0,91.0,598.0,93.0,594.0,90.7,565.0,91.9,...,93.9,178.0,94.2,270.0,90.5,286.0,93.2,274.0,90.7,299.0
29,GA-Fulton/DeKalb Counties,93.9,281.0,90.3,317.0,94.4,289.0,95.7,311.0,93.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,TX-Rest of State,87.0,346.0,92.2,346.0,87.3,278.0,91.9,327.0,89.6,...,92.7,372.0,89.7,454.0,93.3,596.0,88.2,542.0,89.7,599.0
110,Utah,87.7,302.0,89.2,305.0,94.0,274.0,88.6,269.0,89.8,...,92.6,249.0,85.3,263.0,89.2,247.0,88.6,252.0,88.7,249.0
111,Vermont,92.3,322.0,95.2,334.0,94.7,284.0,96.4,288.0,94.4,...,91.2,280.0,93.2,246.0,95.5,262.0,95.2,287.0,93.7,251.0
112,Virginia,91.0,275.0,90.7,243.0,90.3,272.0,92.9,280.0,96.6,...,88.6,274.0,91.5,286.0,83.4,373.0,90.4,368.0,97.6,356.0
113,Washington,89.3,575.0,87.8,600.0,89.6,548.0,93.5,580.0,92.3,...,93.5,222.0,86.3,238.0,95.3,309.0,91.1,320.0,88.5,272.0
114,WA-Eastern WA Counties,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,WA-King County,85.7,264.0,89.0,287.0,92.4,279.0,95.0,293.0,94.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,WA-Western Counties,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,WA-Eastern/Western WA Counties,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,WA-Rest of State,90.7,311.0,87.4,313.0,88.5,269.0,92.9,287.0,91.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,West Virginia,92.6,277.0,93.4,288.0,93.6,256.0,88.7,228.0,94.6,...,86.0,213.0,88.9,259.0,86.7,241.0,89.6,235.0,89.9,298.0
120,Wisconsin,91.3,559.0,91.4,605.0,92.9,552.0,94.2,516.0,93.6,...,93.2,221.0,93.2,240.0,92.4,245.0,90.6,221.0,89.9,218.0
121,WI-Milwaukee County,82.9,275.0,88.4,315.0,90.1,265.0,96.8,262.0,94.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,WI-Rest of State,93.7,284.0,92.3,290.0,93.6,287.0,93.4,254.0,93.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,Wyoming,89.8,328.0,89.0,287.0,89.7,268.0,90.8,270.0,92.7,...,89.0,196.0,90.4,218.0,93.5,219.0,88.8,250.0,89.1,267.0
124,Guam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,90.3,314.0,82.5,266.0
125,Puerto Rico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,85.7,296.0,NaN,NaN
126,U.S. Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,70.5,284.0,NaN,NaN
127,United States,90.0,23102.0,91.1,23642.0,91.6,21410.0,93.0,21310.0,93.0,...,91.9,13611.0,91.5,14893.0,91.9,15167.0,91.1,14988.0,91.5,15333.0
128,Region 1,95.0,2130.0,92.9,2219.0,95.1,1971.0,97.0,1923.0,95.1,...,94.2,1376.0,94.3,1414.0,94.1,1507.0,96.4,1603.0,96.3,1544.0
129,Region 2,92.0,1223.0,91.9,1231.0,93.9,1052.0,94.6,1053.0,95.2,...,95.5,733.0,93.2,728.0,92.6,838.0,93.7,814.0,91.4,899.0
130,Region 3,91.5,2328.0,93.3,2327.0,92.5,2099.0,93.3,2201.0,95.4,...,92.1,1824.0,92.2,2030.0,89.6,2103.0,92.2,2073.0,93.5,2059.0
131,Region 4,90.7,4029.0,92.9,4110.0,92.1,3839.0,93.8,3865.0,93.5,...,93.0,1671.0,92.8,1950.0,91.3,2035.0,91.6,2064.0,91.6,2192.0
132,Region 5,89.9,3346.0,90.1,3607.0,92.7,3381.0,93.6,3177.0,93.1,...,90.1,1615.0,92.5,1807.0,90.9,1797.0,90.6,1684.0,90.6,1712.0
133,Region 6,86.7,3088.0,89.3,3220.0,88.1,2709.0,90.8,2748.0,89.7,...,91.5,2013.0,90.8,2341.0,92.3,2416.0,90.1,2243.0,90.7,2537.0
134,Region 7,90.4,1132.0,90.4,1135.0,93.8,1127.0,92.1,1078.0,93.1,...,91.1,848.0,92.0,942.0,93.2,964.0,93.6,939.0,89.1,893.0
135,Region 8,87.7,1888.0,90.9,1849.0,91.7,1633.0,87.8,1631.0,90.9,...,89.2,1424.0,88.3,1554.0,91.8,1416.0,89.0,1453.0,89.0,1462.0
136,Region 9,89.3,2445.0,90.3,2435.0,90.3,2209.0,92.5,2261.0,92.9,...,90.8,1078.0,89.7,1139.0,92.6,1086.0,89.2,1026.0,92.7,1060.0
137,Region 10,89.3,1493.0,87.9,1509.0,88.3,1390.0,92.9,1373.0,92.5,...,91.9,1029.0,86.7,988.0,94.1,1005.0,89.2,1089.0,89.5,975.0
138,HP 2020 Target,90.0,NaN,90.0,NaN,90.0,NaN,90.0,NaN,90.0,...,90.0,NaN,90.0,NaN,90.0,NaN,90.0,NaN,90.0,NaN

In [129]:
aut_df_two = aut_df_one[['year', 'abbr', 'male.prev', 'female.prev']].copy()
aut_df_three = aut_df_two.rename(columns={'male.prev':'male_prev', 'female.prev':'female_prev'})
aut_df_three.head()

KeyError: "None of [Index(['year', 'abbr', 'male.prev', 'female.prev'], dtype='object')] are in the [columns]"

In [130]:
vax_df_three = vax_df_two[~vax_df_two['Names'].str.contains('-') & ~vax_df_two['Names'].str.contains('Region')]
vax_df_four = vax_df_three[vax_df_three.columns.drop(list(vax_df_three.filter(regex='SAMPLE')))]

In [131]:
vax_df_four.head()

,Names,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Alabama,86.8,94.3,91.6,91.2,91.8,94.1,94.0,95.0,93.6,95.4,95.4,94.0,93.1,89.7,92.0,95.2,91.1,92.3
3,Alaska,87.9,87.8,88.7,90.7,89.7,90.8,85.7,89.7,88.4,85.2,88.4,90.8,86.2,90.5,90.2,89.7,85.6,89.3
4,Arizona,88.1,88.8,88.9,91.5,92.9,88.8,87.7,89.0,92.2,90.8,87.7,86.7,88.3,91.4,84.1,90.6,87.7,91.7
7,Arkansas,88.0,89.1,92.8,90.6,94.6,89.0,85.8,92.5,92.2,81.8,90.5,93.7,92.3,88.3,89.1,90.2,92.1,92.6
8,California,89.4,90.8,90.4,92.8,93.1,91.6,92.8,94.6,92.7,89.8,91.4,91.0,91.5,90.7,90.5,92.8,89.3,92.9

In [132]:
col = aut_df_three.loc[: , "male_prev":"female_prev"]
aut_df_three['prev_mean'] = col.mean(axis=1)
#used this one
aut_df_four = aut_df_three[aut_df_three.columns.drop(list(aut_df_three.filter(regex='male')))]

In [133]:
#used this one
aut_df_five = aut_df_four.transpose()
import numpy as np
aut_df_five = aut_df_five.replace(np.nan, 'unknown', regex=True)
aut_df_five

,0,1,2,3,4,5,6,7,8,9,...,76,77,78,79,80,81,82,83,84,85
year,2000,2000,2000,2000,2000,2000,2002,2002,2002,2002,...,2014,2014,2014,2014,2014,2014,2014,2014,2014,2014
abbr,AZ,GA,MD,NJ,SC,WV,AL,AZ,AR,CO,...,AR,CO,GA,MD,MN,MO,NJ,NC,TN,WI
prev_mean,6.45,6.5,5.4,9.55,6.3,4.5,3.2,6.15,6.8,5.8,...,12.95,13.65,16.8,19.95,23.75,13.9,28.9,17.25,15.35,13.9

In [134]:
aut_df_six = aut_df_four.pivot_table(index='year', columns='abbr')['prev_mean']
aut_df_six

abbr,AL,AR,AZ,CO,FL,GA,MD,MN,MO,NC,NJ,PA,SC,TN,UT,WI,WV
year,,,,,,,,,,,,,,,,,
2000,NaN,NaN,6.45,NaN,NaN,6.50,5.40,NaN,NaN,NaN,9.55,NaN,6.30,NaN,NaN,NaN,4.5
2002,3.20,6.80,6.15,5.80,NaN,7.50,6.60,NaN,7.20,6.35,10.40,5.25,5.95,NaN,7.35,5.10,7.0
2004,4.55,NaN,9.70,NaN,NaN,8.85,8.65,NaN,8.15,8.60,NaN,NaN,5.20,NaN,NaN,7.85,NaN
2006,6.00,NaN,11.90,7.45,4.15,10.00,9.00,NaN,12.00,10.20,NaN,8.30,8.45,NaN,NaN,7.50,NaN
2008,4.60,10.55,15.25,11.50,7.10,11.70,12.20,NaN,13.75,14.10,20.00,13.25,10.90,NaN,21.70,7.70,NaN
2010,5.60,15.35,15.55,9.75,NaN,15.45,16.30,NaN,14.05,17.15,21.75,NaN,NaN,NaN,18.30,9.20,NaN
2012,NaN,8.75,14.95,10.65,NaN,15.40,17.80,NaN,11.35,16.75,24.20,NaN,12.25,NaN,17.05,10.65,NaN
2014,NaN,12.95,13.85,13.65,NaN,16.80,19.95,23.75,13.90,17.25,28.90,NaN,NaN,15.35,NaN,13.90,NaN

In [149]:

vax_df_five = vax_df_four.transpose()
vax_df_five

,0,3,4,7,8,17,20,21,22,23,...,112,113,119,120,123,124,125,126,127,138
Names,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Guam,Puerto Rico,U.S. Virgin Islands,United States,HP 2020 Target
2000,86.8,87.9,88.1,88,89.4,86.4,96.1,90.1,85.1,89,...,91,89.3,92.6,91.3,89.8,NaN,NaN,NaN,90,90
2001,94.3,87.8,88.8,89.1,90.8,91.3,93.8,93.4,92.6,91.1,...,90.7,87.8,93.4,91.4,89,NaN,NaN,NaN,91.1,90
2002,91.6,88.7,88.9,92.8,90.4,90.7,95.3,95.2,91.2,91.1,...,90.3,89.6,93.6,92.9,89.7,NaN,NaN,NaN,91.6,90
2003,91.2,90.7,91.5,90.6,92.8,85.6,98.4,93,92.8,95.2,...,92.9,93.5,88.7,94.2,90.8,NaN,NaN,NaN,93,90
2004,91.8,89.7,92.9,94.6,93.1,90.8,95,94.5,94.6,95.4,...,96.6,92.3,94.6,93.6,92.7,NaN,NaN,NaN,93,90
2005,94.1,90.8,88.8,89,91.6,93.2,95.2,95.2,91.6,92,...,93.3,90.6,85.7,91.6,89.4,NaN,NaN,NaN,91.5,90
2006,94,85.7,87.7,85.8,92.8,88.3,96.5,96.4,92.2,91.2,...,93.6,87.5,91.1,94,87.7,NaN,NaN,NaN,92.3,90
2007,95,89.7,89,92.5,94.6,91.2,95.3,94.8,95.2,92.3,...,90.9,90.5,96.2,91.4,87.5,NaN,NaN,NaN,92.3,90
2008,93.6,88.4,92.2,92.2,92.7,92.3,95.3,93.1,89.7,91.7,...,92.3,91.2,88.3,94.3,87.6,NaN,NaN,NaN,92.1,90
2009,95.4,85.2,90.8,81.8,89.8,83.6,93.7,90.2,91.2,91.2,...,85.8,90.8,89.2,94.4,91.3,NaN,NaN,71.2,90,90
2010,95.4,88.4,87.7,90.5,91.4,89.3,97.8,94,94.7,94.1,...,92.3,89.8,92,93.2,92.5,NaN,NaN,72.6,91.5,90
2011,94,90.8,86.7,93.7,91,88.4,95,90.6,93.5,90.8,...,89,89.3,85.8,94.9,85.6,NaN,NaN,73.6,91.6,90
2012,93.1,86.2,88.3,92.3,91.5,91.5,94.8,94.4,93,91,...,94.3,84.8,84.6,89.3,91.2,NaN,NaN,63.7,90.8,90
2013,89.7,90.5,91.4,88.3,90.7,86,91.4,94.8,96.2,93.4,...,88.6,93.5,86,93.2,89,NaN,NaN,NaN,91.9,90
2014,92,90.2,84.1,89.1,90.5,87.4,93.2,90.8,90.9,91.2,...,91.5,86.3,88.9,93.2,90.4,NaN,NaN,NaN,91.5,90
2015,95.2,89.7,90.6,90.2,92.8,93.6,97.5,97.2,92.4,90.4,...,83.4,95.3,86.7,92.4,93.5,NaN,NaN,NaN,91.9,90
2016,91.1,85.6,87.7,92.1,89.3,88.9,94.5,93.8,93.7,91.1,...,90.4,91.1,89.6,90.6,88.8,90.3,85.7,70.5,91.1,90
2017,92.3,89.3,91.7,92.6,92.9,87.2,94.6,92.9,94.1,91.9,...,97.6,88.5,89.9,89.9,89.1,82.5,NaN,NaN,91.5,90

In [150]:
aut_df_six = aut_df_four.pivot_table(index='abbr', columns='year')['prev_mean']
aut_df_six

year  2000   2002  2004   2006   2008   2010   2012   2014
abbr
AL     NaN   3.20  4.55   6.00   4.60   5.60    NaN    NaN
AR     NaN   6.80   NaN    NaN  10.55  15.35   8.75  12.95
AZ    6.45   6.15  9.70  11.90  15.25  15.55  14.95  13.85
CO     NaN   5.80   NaN   7.45  11.50   9.75  10.65  13.65
FL     NaN    NaN   NaN   4.15   7.10    NaN    NaN    NaN
GA    6.50   7.50  8.85  10.00  11.70  15.45  15.40  16.80
MD    5.40   6.60  8.65   9.00  12.20  16.30  17.80  19.95
MN     NaN    NaN   NaN    NaN    NaN    NaN    NaN  23.75
MO     NaN   7.20  8.15  12.00  13.75  14.05  11.35  13.90
NC     NaN   6.35  8.60  10.20  14.10  17.15  16.75  17.25
NJ    9.55  10.40   NaN    NaN  20.00  21.75  24.20  28.90
PA     NaN   5.25   NaN   8.30  13.25    NaN    NaN    NaN
SC    6.30   5.95  5.20   8.45  10.90    NaN  12.25    NaN
TN     NaN    NaN   NaN    NaN    NaN    NaN    NaN  15.35
UT     NaN   7.35   NaN    NaN  21.70  18.30  17.05    NaN
WI     NaN   5.10  7.85   7.50   7.70   9.20  10.65  13.90
WV    4.50   7.00   NaN    NaN    NaN    NaN    NaN    NaN

In [151]:
state = list(aut_df_six.index.values)

In [152]:
aut_df_seven = aut_df_six.reset_index(drop=True)
aut_df_seven['abbr'] = state
aut_df_seven.head()

year  2000  2002  2004   2006   2008   2010   2012   2014 abbr
0      NaN  3.20  4.55   6.00   4.60   5.60    NaN    NaN   AL
1      NaN  6.80   NaN    NaN  10.55  15.35   8.75  12.95   AR
2     6.45  6.15  9.70  11.90  15.25  15.55  14.95  13.85   AZ
3      NaN  5.80   NaN   7.45  11.50   9.75  10.65  13.65   CO
4      NaN   NaN   NaN   4.15   7.10    NaN    NaN    NaN   FL

In [153]:
rds_connection_string = "postgres:postgres@localhost:5432/mypythonETLdata"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [154]:
engine.table_names()

['states', 'mmr', 'autism']

In [157]:
vax_df_four.to_sql(name='mmr', con=engine, if_exists='append', index=False)
#after I dropped the MMR table in postgres so that Names is now "Names"

In [158]:
aut_df_seven.to_sql(name='autism', con=engine, if_exists='append', index=False)